// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEFGallery.API.Data;

#nullable disable

namespace UEFGallery.API.Migrations
{
    [DbContext(typeof(GalleryDbContext))]
    partial class GalleryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UEFGallery.API.Models.Artwork", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("TEXT")
                        .HasColumnName("academic_year");

                    b.Property<int?>("AiGeneratedPct")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ai_generated_pct");

                    b.Property<int?>("AiScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ai_score");

                    b.Property<string>("BlocksJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("blocks_json");

                    b.PrimitiveCollection<string>("CollaboratorIds")
                        .HasColumnType("TEXT")
                        .HasColumnName("collaborator_ids");

                    b.PrimitiveCollection<string>("Collaborators")
                        .HasColumnType("TEXT")
                        .HasColumnName("collaborators");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("FileUrls")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_urls");

                    b.Property<bool>("IsAiConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ai_confirmed");

                    b.Property<bool>("IsAiVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ai_verified");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_highlighted");

                    b.Property<bool>("IsPending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pending");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_public");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("like_count");

                    b.Property<string>("OriginalCoverUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_cover_url");

                    b.Property<string>("PortfolioSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_slug");

                    b.Property<string>("Semester")
                        .HasColumnType("TEXT")
                        .HasColumnName("semester");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.PrimitiveCollection<string>("ToolsUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("tools_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("view_count");

                    b.Property<string>("WatermarkImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("watermark_image_url");

                    b.Property<string>("WatermarkPosition")
                        .HasColumnType("TEXT")
                        .HasColumnName("watermark_position");

                    b.Property<string>("WatermarkText")
                        .HasColumnType("TEXT")
                        .HasColumnName("watermark_text");

                    b.HasKey("Id")
                        .HasName("pk_artworks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_artworks_user_id");

                    b.ToTable("artworks", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.ArtworkBadge", b =>
                {
                    b.Property<string>("ArtworkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_at");

                    b.HasKey("ArtworkId", "BadgeId")
                        .HasName("pk_artwork_badges");

                    b.HasIndex("BadgeId")
                        .HasDatabaseName("ix_artwork_badges_badge_id");

                    b.ToTable("artwork_badges", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("badge_id");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lecturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text_color");

                    b.HasKey("Id")
                        .HasName("pk_badges");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("ix_badges_lecturer_id");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.CollectionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("collection_item_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("ArtworkId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<string>("CollectionName")
                        .HasColumnType("TEXT")
                        .HasColumnName("collection_name");

                    b.Property<string>("CuratorEssay")
                        .HasColumnType("TEXT")
                        .HasColumnName("curator_essay");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lecturer_id");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT")
                        .HasColumnName("theme");

                    b.HasKey("Id")
                        .HasName("pk_collection_items");

                    b.HasIndex("ArtworkId")
                        .HasDatabaseName("ix_collection_items_artwork_id");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("ix_collection_items_lecturer_id");

                    b.ToTable("collection_items", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment_id");

                    b.Property<string>("ArtworkId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double?>("PositionX")
                        .HasColumnType("REAL")
                        .HasColumnName("position_x");

                    b.Property<double?>("PositionY")
                        .HasColumnType("REAL")
                        .HasColumnName("position_y");

                    b.Property<int?>("TargetImageIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_image_index");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ArtworkId")
                        .HasDatabaseName("ix_comments_artwork_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Follow", b =>
                {
                    b.Property<string>("FollowerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("follower_id");

                    b.Property<string>("FollowedId")
                        .HasColumnType("TEXT")
                        .HasColumnName("followed_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("FollowerId", "FollowedId")
                        .HasName("pk_follows");

                    b.HasIndex("FollowedId")
                        .HasDatabaseName("ix_follows_followed_id");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Grade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("grade_id");

                    b.Property<string>("ArtworkId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVisibleToStudent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_visible_to_student");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lecturer_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grades");

                    b.HasIndex("ArtworkId")
                        .HasDatabaseName("ix_grades_artwork_id");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("ix_grades_lecturer_id");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Like", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("like_id");

                    b.Property<string>("ArtworkId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reaction_type");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_likes");

                    b.HasIndex("ArtworkId")
                        .HasDatabaseName("ix_likes_artwork_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_likes_user_id");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsEmailed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_emailed");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasColumnName("purpose");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_id");

                    b.Property<string>("SenderCompany")
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_company");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_name");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_messages_recipient_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_id");

                    b.Property<string>("ActorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.PortfolioSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_id");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("banner_url");

                    b.Property<bool>("ContactEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_enabled");

                    b.Property<string>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_order");

                    b.PrimitiveCollection<string>("FeaturedArtworkIds")
                        .HasColumnType("TEXT")
                        .HasColumnName("featured_artwork_ids");

                    b.Property<bool>("IsPortfolioPublic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_portfolio_public");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("major");

                    b.Property<string>("PortfolioSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_slug");

                    b.Property<string>("ProfileHeadline")
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_headline");

                    b.Property<bool>("ShowEmail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_email");

                    b.Property<string>("SocialLinks")
                        .HasColumnType("TEXT")
                        .HasColumnName("social_links");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("YearLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("year_level");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolio_settings_user_id");

                    b.ToTable("portfolio_settings", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("report_id");

                    b.Property<string>("ArtworkId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artwork_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("violation_type");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ArtworkId")
                        .HasDatabaseName("ix_reports_artwork_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reports_user_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.SiteSection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("section_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("page");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("section");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_site_sections");

                    b.ToTable("site_sections", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.SiteSectionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_site_section_items");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_site_section_items_section_id");

                    b.ToTable("site_section_items", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.SiteSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_site_settings");

                    b.ToTable("site_settings", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.TimelineEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("LinkLabel")
                        .HasColumnType("TEXT")
                        .HasColumnName("link_label");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("link_url");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("month");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_timeline_entries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_timeline_entries_user_id");

                    b.ToTable("timeline_entries", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT")
                        .HasColumnName("bio");

                    b.Property<string>("Cohort")
                        .HasColumnType("TEXT")
                        .HasColumnName("cohort");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("TEXT")
                        .HasColumnName("email_verified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT")
                        .HasColumnName("major");

                    b.PrimitiveCollection<string>("ManagedClasses")
                        .HasColumnType("TEXT")
                        .HasColumnName("managed_classes");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<string>("ResetCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_code");

                    b.Property<DateTime?>("ResetCodeExpires")
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_code_expires");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("verification_code");

                    b.Property<DateTime?>("VerificationCodeExpires")
                        .HasColumnType("TEXT")
                        .HasColumnName("verification_code_expires");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UEFGallery.API.Models.Artwork", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithMany("Artworks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artworks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.ArtworkBadge", b =>
                {
                    b.HasOne("UEFGallery.API.Models.Artwork", "Artwork")
                        .WithMany("ArtworkBadges")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artwork_badges_artworks_artwork_id");

                    b.HasOne("UEFGallery.API.Models.Badge", "Badge")
                        .WithMany("ArtworkBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artwork_badges_badges_badge_id");

                    b.Navigation("Artwork");

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Badge", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_badges_users_lecturer_id");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("UEFGallery.API.Models.CollectionItem", b =>
                {
                    b.HasOne("UEFGallery.API.Models.Artwork", "Artwork")
                        .WithMany("CollectionItems")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_items_artworks_artwork_id");

                    b.HasOne("UEFGallery.API.Models.User", "Lecturer")
                        .WithMany("Collections")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_items_users_lecturer_id");

                    b.Navigation("Artwork");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Comment", b =>
                {
                    b.HasOne("UEFGallery.API.Models.Artwork", "Artwork")
                        .WithMany("Comments")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_artworks_artwork_id");

                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Artwork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Follow", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_followed_id");

                    b.HasOne("UEFGallery.API.Models.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_follows_users_follower_id");

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Grade", b =>
                {
                    b.HasOne("UEFGallery.API.Models.Artwork", "Artwork")
                        .WithMany("Grades")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_artworks_artwork_id");

                    b.HasOne("UEFGallery.API.Models.User", "Lecturer")
                        .WithMany("GradesGiven")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_users_lecturer_id");

                    b.Navigation("Artwork");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Like", b =>
                {
                    b.HasOne("UEFGallery.API.Models.Artwork", "Artwork")
                        .WithMany("Likes")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_artworks_artwork_id");

                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_likes_users_user_id");

                    b.Navigation("Artwork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Message", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "Recipient")
                        .WithMany("Messages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Notification", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.PortfolioSetting", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithOne("PortfolioSettings")
                        .HasForeignKey("UEFGallery.API.Models.PortfolioSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Report", b =>
                {
                    b.HasOne("UEFGallery.API.Models.Artwork", "Artwork")
                        .WithMany("Reports")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_artworks_artwork_id");

                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_reports_users_user_id");

                    b.Navigation("Artwork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.SiteSectionItem", b =>
                {
                    b.HasOne("UEFGallery.API.Models.SiteSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_section_items_site_sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UEFGallery.API.Models.TimelineEntry", b =>
                {
                    b.HasOne("UEFGallery.API.Models.User", "User")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timeline_entries_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Artwork", b =>
                {
                    b.Navigation("ArtworkBadges");

                    b.Navigation("CollectionItems");

                    b.Navigation("Comments");

                    b.Navigation("Grades");

                    b.Navigation("Likes");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("UEFGallery.API.Models.Badge", b =>
                {
                    b.Navigation("ArtworkBadges");
                });

            modelBuilder.Entity("UEFGallery.API.Models.SiteSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UEFGallery.API.Models.User", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("Collections");

                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("GradesGiven");

                    b.Navigation("Likes");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("PortfolioSettings");

                    b.Navigation("Reports");

                    b.Navigation("TimelineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
